### ISSUE TITLE
Keyboard shortcut interferes with other global hotkeys

### ISSUE THREAD

**Issue by ghost** [lestcape/Configurable-Menu#64]
If keyboard shortcut is set to Super_L then it is no longer possible to execute other shortcuts that involve Super_L key. Maybe it would work if menu opened upon key release instead of key-press?

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.

**Comment by mtwebster** [comment]
This is incorrect.  The route to submitting extensions, and the hosting of them was changed, in order to improve security and transparency.  Nothing at all is stopping you from continuing to host your development sources for this applet elsewhere, then submitting the latest version to the hosting system.

Any patches made to the 'official' source repositories by other than the original author are done so either by permission of said author, either blanket or explicit, or fixes for unavoidable breakages (such as that may occur across the board due to api changes, where any sort of 'revert' is not an option.)

As for translations, I seriously doubt that if we were to provide a separate package called "all-applets-translations" and it magically translated your applets into 20 additional languages, you would not complain one bit.  You would probably thank us, in fact.  The fact that we add them to each applet's package individually is an organizational decision only.

It is all explained here: http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/

*YOU* are still the owner of any applets you wrote.  You *can* and *did* ask for their removal, and this was respected.  Nothing was stolen/forked from you - all this extra noise is just grandstanding.  I would have liked to see you go the other way, and become more involved, to the point, somewhere in the future, that you could gain access to doing your own merges, reviews, etc.. and helping others to do the same.

I understand both sides of this, don't get me wrong, but in the end security and end-user experience comes first - all should agree - and part of dealing with other people and organizations is compromise and understanding and attempting to see all sides of the situation.

Looking at this post-implementation, I really don't see how any rights or freedoms have been trampled in a practical sense - any developer that wants to, has full control and ownership over their creations, the same as before.  The only addition is of a sort of 'firewall' to prevent malicious activity.   If anything, it's *more open than before* - we can be guaranteed that the extension we install to our desktop is precisely that which is hosted on github.  This wasn't always the case - many developers didn't host their code publicly.  Additionally, core Cinnamon developers can better communicate and/or fix any breakages they cause, more translations can be made (this is continually being worked on to make it easier to participate in,) and abandoned applets that haven't been worked on in some time are being fixed (if I recall in an old discussion, even you were encouraging of this).

I wish you well wherever you go - however I wish you could see things otherwise.  I have a feeling there are social and/or political influences at work here that perhaps are influencing perspectives and reactions.

**Comment by lestcape** [comment]
@mtwebster thanks for all explanation of how you see this. Sorry in this case, as there are not anything incorrect here. It's out of my decisions where the things will go for a Mint project and also it's out of your own decision, as you are not the leader of the Mint team...

It's for me really very important have your opinion about all this, because this come from you and i always see you as an excellent developer with a long range of things where you can work. More than that, you are a nice people that want to contribute in all things where you can and also more than that. You always are there to listen the users comments in one way or in another and you always want to do the best of you.

You are making a lot of nice things for users and for developers and i'm pretty conscience that more than what this things can be retrieve to you, if in fact, some of this things could get you something different to your satisfaction to help where you considered useful and/or because will go in the right direction or just in your same direction...

I will be also happy to help users, all type of users. I really have not the time to do all that I will want to do. Then i need to select only the things that will go in the direction that i considered right.

I do not considered right:
- Change or override a developer code without his approval. Not also to fix something, to add language support or whatever. You always can fork the repository and make this in your name (in that case in the Mint name). If really this causing a problem to some one and you want to resolved it, but never do that in the name of a developer or using a canal that was give it to him to only share his code to all users in the same platform. What spices was some days ago, a platform like launchpad, where developer was free to decided what they want to do, when they want to do that and also users could decided if they want to install something, when hi want to install it and how he want to install it. This is an issue like if the google corporation decide used my account to answer all my emails, because they considered right make it in your name, because people are waiting for an answer. 

- I don't considered right just change all the model and do not give to the developers any alternative way of continues doing the think in his name, how they was doing the things. This is wrong for developers, wrong for cinnamon, wrong for users and wrong for Mint. Because there are people like me that want to do his own things along and then, users won't have a new feature, cinnamon won't have a new feature, Mint won't have a new feature.

What Clement do, was dictate an arbitrary rule and imposition, that i considered out of all ethics. I sorry then but i will not work in that conditions if there are not respect for the work of others, whether this work could be good or bad, not matter. This never can be a question, as never i see in spices an extension that was make with the intention of cause a damage. 

Non of you have the right to open any email inbox of any of your developers (spices users ) and answer the emails that they have without see.  That is the intention of the new model. Open the inbox of all users and answer all his emails. Will be good for user that are waiting for an answer, but never ok, for developers.

There are currently a lot of developers that don't know his inbox was violated, form the owner of his hosted services.

**Comment by cinnamoner** [comment]
I'm trying to identify the similarities and/or discreapancies to the KDE Store.

**Comment by lestcape** [comment]
@mtwebster To be more clear: **My confidence is over, and it is clear that I will not work in trying to help those who respect neither limits nor my privacy, who limits my power of decision or questions the my honesty, good judgment and intention of what I make for users. Because anyone who does this becomes my enemy.**

**Comment by lestcape** [comment]
@cinnamoner i don't know, but this is not my point,  you can open an store and set all rules you want and that is not a problem. A problem it's set rules in a place that was a free environment (or i supposed it was). The problem is not be consequent, the problem is change the rules in a way that is good for you and make this in the name of the clients, and then decide about  how your products will be sold, or change what they do, all this without know your opinion against his own rules and thinking only because are there are his products and not yours, so they can decide what they want and change it like hi want, but sold it like was your who do that. That is my point.

**Comment by lestcape** [comment]
This is probably the reason why I am so individualistic in this respect:

I was born in a communist country where individual decisions were never taken into account, where the right to individuality does not exist, where you can not make personal decisions. I'm sick of it. No one is going to be able to erase that from me. No one is going to make it part of that crap.

**Comment by lestcape** [comment]
If this is not understand perfectly, read the point 4, and don't believed me. This is about ethics in open source: https://opensource.org/docs/definition.php

**Comment by lestcape** [comment]
@mtwebster just see how you are wrong:
https://github.com/linuxmint/cinnamon-spices-applets/pull/121
https://github.com/linuxmint/cinnamon-spices-applets/pull/27
