### ISSUE TITLE
Removing "All Applications" feature

### ISSUE THREAD

**Issue by brittonf** [lestcape/Configurable-Menu#76]
I was wondering if you could help me remove the All Applications button/feature in the menu. I have messed around with the javascript but without total success (text disappears, but not functionality, crashes, etc). The feature seems very intertwined with a lot of other functionality, so it appears difficult. If you could point out general directions that would be very helpful. Any code I come up with from there I will gladly give back to the project.
Thank you!

**Comment by lestcape** [comment]
on the _initialDisplay: add this line: 
```
  if((!this.categoriesExcludes)|| this.categoriesExcludes.indexOf(this._categoryButtons[i].getCategoryID()) == -1))
```

```
_initialDisplay: function() {
      if(!this.displayed) {
         this.displayed = true;
         for(let i = 0; i < this._categoryButtons.length; i++) {
            if((!this.categoriesExcludes)||(this.categoriesExcludes.indexOf(this._categoryButtons[i].getCategoryID()) == -1))
                this._categoryButtons[i].actor.show();
         }
```
on _updateComplete add this two lines at the begin:

```
   _updateComplete: function() {
      this.categoriesExcludes = new Array();
      this.categoriesExcludes.push("All");
```

Tell me if this is what you want...

**Comment by lestcape** [comment]
Will be impossible remove "All application" from the menu without a big change... The solution is hide the actor... The problem is that this feature is related with all important things on the menu, like the performance, the search, the default category for the first time that menu is open and more important things... What i do is use a behavior(hide the categories that i want) that i implemented to be used on an specific layout now as a general option and now only for the all application category.

**Comment by brittown** [comment]
hey lestcape that works great. They all show in the beginning but i am good with that, especially with the small amount of code that needed to be changed. I might take it further and see if i can tweak it so a different category shows upon opening. If i succeed i will post here. Thanks so much

**Comment by lestcape** [comment]
@brittown i'm not recommend you try to do a thing like that.... It's because could impact on the menu performance... 

Please see:

https://www.google.com.mx/search?client=ubuntu&channel=fs&q=cinnamon+menu+slow+to+open&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=EcQIVe3ALI7CrAbm7IHQBg

What could solved this problem is show the application icons on an special way when the menu start, if you don't show all icons they will reduce the performance when you change the categories... Please see, this is not a easy thing:
https://github.com/lestcape/Configurable-Menu/issues/42

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
