### ISSUE TITLE
Broken in Cinnamon 2.6.13

### ISSUE THREAD

**Issue by sgleizes** [lestcape/Configurable-Menu#82]
Hello,

I have been trying the latest development version from the master branch, it turns the red light indicator on when adding it to the panel.
Unfortunately I couldn't find a more specific error, as I haven't been able to find any logs.

Please let me know if and how I can be of any help to find more information.
Thanks.

**Comment by lestcape** [comment]
Configurable Menu is working on my system and this is my output :

lestcape@Vampire:~$ cinnamon --version
Cinnamon 2.6.13
lestcape@Vampire:~$ 

Can you please delete the folder: ~/.cinnamon/configs/configurableMenu@lestcape and try to enable the configurable menu again?

If is not working after enable it, please copy the content of the file ~/.xsession-errors and /.cinnamon/glass.log here. You need enable in nemo the option to show hidden files and folder to see all this path...

Thanks for your report.

Regrads.

**Comment by sgleizes** [comment]
I have the same output regarding the cinnamon version.
I deleted the folder but same behavior.

Nothing is outputed to `.xsessions-errors` when adding/removing the applet.
The only relevant line in glass.log:

```
info t=2015-09-19T23:26:32.613Z Loaded applet configurableMenu@lestcape in 50 ms
```

**Comment by lestcape** [comment]
Ups... Sorry, but i have not idea of what occurs. i know there are several problems with configurable menu and the new version of cinnamon, but at less configurable menu can be displayed in 2.6.13.

**Comment by bluedxca93** [comment]
hi, 
in 2.6.13 and 2.8 it displays repos.source actor not found, and in win7 style it doesnt show application switcher label text. unlike stark menu also affected by this bug the menu favorites switcher is not working too.
will there be a fix? i only need the menu with the quicklings, not favoites if thats easier to do.

**Comment by cwilli34** [comment]
I just sent a pull request that will hopefully fix this particular issue.  I know that lestcape has broken the code up into multiple files, but if you have just one applet.js file in your `configurableMenu@lestcape` directory (you can find at `/home/[username]/.local/share/cinnamon/applets/`), you can replace that applet.js with the file I am attaching.  It fixes it on my version of cinnamon (2.8.5).  Let me know if it doesn't fix yours.  Just change the extension of the file to `.js`

Right now, if I clone what is here in this repository, this applet does not work.  I have installed Configurable-Menu through the Applets settings in cinnamon and edited the applet.js file.

[applet.txt](https://github.com/lestcape/Configurable-Menu/files/49887/applet.txt)

**Comment by bluedxca93** [comment]
hi,
maybe please publish a diff from the version you modified. Do testing your revision next week then and rewrite here if it works then.
i hope so since configurable menu offers so much functionality to cinnamon.

**Comment by bluedxca93** [comment]
hi,

that bugfix you suggested doesnt run correctly on my system damn.

any idea how to replace popup.popupsubmenuitem.prototype with
popup.popupbasemenuitem.prototype ?

how to define action to exec when clicked for basemenuitem.

reason both configurable and stark menu want older 2.6.10 styled definition.
that is one problem. partially fixed in configurable menu.

another one is repos source actor not found.

regards bluedxca93

**Comment by cwilli34** [comment]
Sorry @bluedxca93, I was a little premature in regards to what I was fixing.  My fix only took care of the popup issue regarding repos, allowing the menu to open correctly without the error.  The right-click issue is definitely still there, and after listening to @lestcape, issues go far beyond that with the memory leaks and duplicate code.  I haven't had time to look at this any further unfortunately.  I would like to pick this up actually, but I just simply don't have the time right now.  I will look further into it later if I do find time and no one else does.

**Comment by bluedxca93** [comment]
hi,

well i see the following things at the moment:

1) if cinnamon gets boxpointer distance from screen edge themable in
later version the positioning can be entirely made by original
cinnamon css files. so no need to include older now not working  box
pointer code.

It might be easier to delete all or parts of the custom boxpointer
définition in configurable menu mostly cause of win 7 layout. Better a
working stable menu, than one a little bit more flexible crashing too
often.

2) popupsubmenu prototype needs to be forked for some custom buttons
on some few layouts only .No real need to care about speed since its
constructed on the popup menu base item like before and the number of
these buttons is low.Other forked menu definition may be deleted and
referred to.cinnamon internal ones.where it makes sense.

3) some click on button nothing happens.and shortcut problems most
likely related to 1 and 2.

and.yes patching an earlier version to.be 2.8 compatible and then fixing
memory leaks seems.easier. do look if i can get an version working.

regards bluedxca93

**Comment by lestcape** [comment]
@bluedxca93 unfortunately what you say can not be. I need a fork of the boxpointer for several things, not only the distance between the menu and the screen border. When you try to resize the menu you can see a triangle where you can resize it. To show this triangle i need a hard painting inside the boxpointer fork, for example.

**Comment by lestcape** [comment]
@cwilli34 the resize feature is implemented in a wrong way. The idea is create a GridBoxLayout like the FavoritesBox where we can encapsulate his functions and in this way will reduced a lot of code, also the resize feature is controlled in an inverse way. If right now a resize occurs "outside", then "inside" the box not occurs anything (for the menu items). To perform a change I need to remove all items and add the items again to find the appropriate number of columns in the grid. What need to be is that we need capture the allocation change and then find if the internal actors also need to be allocated, for fill the space. In this way we only remove and add actors when is really necessary and not all time. Also is possible apply some patches for performance reasons trying to not move all items just some of them when really is needed.

**Comment by lestcape** [comment]
@cwilli34 You can see also a lot of code removed (duplicate code) here: https://github.com/lestcape/Configurable-Menu/commit/9b4040efdc6a2063d47f5a01a36ef5984169a3a3

And also, what occurs about memory i thing is a bug of cinnamon itself. See this function: 
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/applet.js#L337

on_applet_removed_from_panel need to be execute the destroy of the menu:
https://github.com/linuxmint/Cinnamon/blob/master/files/usr/share/cinnamon/applets/menu%40cinnamon.org/applet.js#L1274

If you try to find where the menu is destroyed, you will see that never is destroyed, because if will be destroyed, then they will get a big memory problem like configurable Menu, because i try to destroy things in configurable menu, but they are not property destroyed. Cinnamon Menu apparently  reused the memory involved into create all menu items and never destroy the memory. Thats is a wrong behaviour in my opinion.

**Comment by rodneyrod** [comment]
So what's the progress on this?
I'm trying to get Cinnamon working with Manjaro but in the new release, the menu is light years away from the screen edge, and this seemed like a good option to fix that, but it broke my test install...

**Comment by lestcape** [comment]
@rodneyrod, the menu is not working, and will not work for a lot of time. I'm triying to implement the menu in a different way, as a dependency of my api and not from the cinnamon api. Also i try to increase the performance, reduce a lot of code, reimplemented several options property and not as a patch like currently. This is pretty hard as Configurable Menu have a lot of test cases.

**Comment by lestcape** [comment]
I update configurable menu: You can test it for all standard layout (all but not gnome classic or kicker). Probably you will required a cinnamon restart. Gnome menu (all positions), mint and windows layouts have a lot of bugs yet. The packages search or web search are not working. The navigation keyboard are not working properly. The grid layout is not optimized yet and have a lot of bugs.
