### ISSUE TITLE
[Feature Request] Mouseover for 'Places' subdirectories

### ISSUE THREAD

**Issue by lucidb-x** [lestcape/Configurable-Menu#84]
Thanks I really appreciate the configurable menu. I have it installed on a fresh Mint 17.2 Cinnamon system and it is working great. In the Menu configuration I set: 
- open Menu on mouseover.  (An excellent option I was glad to find.) 

More options that I am using are:
- automatic sizing
- show places 
- open categories on mouseover. 

So, now we are getting to something I have been looking very hard for....   You are so close to including it already I thought I would ask about it here.

When I hover over a category the menu flys out on the right side and shows the contents. Also that fly-out menu sizes itself to fit how many items are in it. I would like this feature to continue happening when hovering over the 'Places' category. So that Documents, or Music or Pictures will also fly out to the right. And if I select a subdirectory in any of them again it too will fly out. All I am doing is hovering deeper and deeper into each one with NO clicking. 

If not the 'Places' category then maybe a more limited one called 'Files' or just 'Home'. This is the most efficient file browsing that I have been using on my old computer.

Is this possible to add? Way too complicated?

**Comment by lestcape** [comment]
Hi, @lucidb-x i really don't know what you say, can you please explain, if you are talking about a specific layout or what? In any case i don't speak english and i cannot understand the concept of fly-out, that you try to explain.

**Comment by lestcape** [comment]
Let me try to say what i can understand. If you are requesting a menu that can explore directories and show the contents in another new panel when you selected the parent folder, beginning for some special folders (places), then i need to say this is not possible to do in general. There are not space in the screen to show all that. What we can do is swapping the panel contents when you select an item, moving the children to the (parent panel) and then display the children of the children in the (children panel), repeating the process when you select another children. The last, is certainly a thing that can be done, but not in all menu layouts.

So, more simple, do you want something similar like some kde menu (i do not remember the name of this menu right now)?

Speaking of the complexity of implement a menu like this, well, is not hard, but if you want to include a feature like this inside the configurable menu then is certainly complex, because of the several layouts and different behaviours...

**Comment by lucidb-x** [comment]
I made a video of my old computer doing what I was trying to explain. Whether it is a feature of your menu or an app on its own I want this feature very much.

https://www.youtube.com/watch?v=fG_8nJ3Zxjs

**Comment by lestcape** [comment]
@lucidb-x ahhh, yes, is not more easy say like the old wind 95, menu style? thanks for the video, anyway...

I want to implement a menu like this, but maybe not for configurable menu, instead in think to add this to global menu. Is really difficult make an api to handle several menu at the same time, but this is done in the global menu api.

See: https://github.com/lestcape/Global-AppMenu/issues/14

**Comment by lucidb-x** [comment]
I searched very hard to add this to my Cinnamon desktop. Some people say this would be a difficult feature to write. 

What I found that has already been done:
http://community.linuxmint.com/software/view/file-browser-applet
https://code.google.com/p/gnome-menu-file-browser-applet/

**Comment by lucidb-x** [comment]
Hi. I found the feature I was asking about. It is an add on in Cairo Dock called quick browser. Not perfect but it is working for a way to do "no click" file browsing.

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
