### ISSUE TITLE
Cinnamon 2.8

### ISSUE THREAD

**Issue by BarnabyWilde** [lestcape/Configurable-Menu#86]
Problems with the menu on Cinnamon 2.8 reported on Mint forum - 
http://forums.linuxmint.com/viewtopic.php?f=47&t=209599

**Comment by legion1978** [comment]
hi there
“repos sourceActor is undefined.” error and notification everytime the menu is active. there are other reports around the web.
this is by far the best menu around. would be nice to have it fixed :) 
thank you

**Comment by cwilli34** [comment]
I just sent a pull request that will hopefully fix this particular issue.  I know that lestcape has broken the code up into multiple files, but if you have just one applet.js file in your `configurableMenu@lestcape` directory (you can find at `/home/[username]/.local/share/cinnamon/applets/`), you can replace that applet.js with the file I am attaching.  It fixes it on my version of cinnamon (2.8.5).  Let me know if it doesn't fix yours.  Just change the extension of the file to `.js`

Right now, if I clone what is here in this repository, this applet does not work.  I have installed Configurable-Menu through the Applets settings in cinnamon and edited the applet.js file.

[applet.txt](https://github.com/lestcape/Configurable-Menu/files/49887/applet.txt)

**Comment by legion1978** [comment]
so far so good. ty :) :+1:

**Comment by cwilli34** [comment]
Np.

**Comment by lestcape** [comment]
Hi.
@cwilli34 thanks for the help.

 Yes, I was working to migrate configurable menu to the changes that was create in the global menu applet. In this way i can reuse the code without losing the time to do the same things. So yes, is more easy fix the oldest version, but well, in any case i have not a lot of time. Configurable menu have a lot of problems, not only this problem is really big and need a lot of attention because override a lot of cinnamon functionality to be possible the implementation of some wanted behaviors. Some of there in a complete different direction of cinnamon, because this is the idea. Configure your menu like you want. After some released of Cinnamon and of course several patches in the new version again and again, The Configurable Menu need a really update or dies. There are a lot of memory leaks when you change the menu, several minor bugs and a lot of duplicate code. I really don't know if i can rewrite Configurable Menu or not, but well if some one can and want is free to do it and continues the project. For me is ok if is a fork of the menu with another name, to not create a collisions if i find the time to continue the migration. 

Regards.

**Comment by cwilli34** [comment]
No problem.  I actually noticed that when you right click on the applet in the panel it still freezes cinnamon, except for opening the menu with a hot-key.  I have to ctrl+alt+backspace to log-out and log back in.  I can't seem to figure out where that issue is coming from yet.

If I had the time I would start a different branch and mess around with fixing those issues with Configurable Menu because I did notice that there is tons of duplicated code, etc., but I really just don't have the time to work on anything extra at this time.  I also have noticed the memory issue to with animations.  I will keep tinkering when I have time.  

But thanks for the reply.  I understand other things come first/are more important.

**Comment by bluedxca93** [comment]
hi,
any idea how to replace
popup.popupsubmenuitem.prototype
with
popup.popupbasemenuitem.prototype ?
how to define action to exec when
clicked for basemenuitem.  ?

just wanted to know if you guys know how to do that. i did get it changed, but the function argument doesnt get executed when pressed.renders fine optically but nothing happens if i press it. can i fork this damn .prototype somehow for a limited number of buttons? .

regards bluedxca93

**Comment by kghbln** [comment]
A fix will be cool. This is the best around and the standard menu is pretty poor. Thumbs up!

**Comment by NikoKrause** [comment]
@lestcape: (and others who can help)

There is a funtion often used in the applet.JS file: this.box = new St.BoxLayout({ style_class: "menu-application-box"})

The menu-application-box is set in the cinnamon.css of the actually used theme.
My question is: Can I do something like:

if(style_class "starkmenu-application-box" exists in cinnamon.css)
this.box = new St.BoxLayout({ style_class: "starkmenu-application-box"})
else
this.box = new St.BoxLayout({ style_class: "menu-application-box"})

**Comment by lestcape** [comment]
@BarnabyWilde 
```
this.box = new St.BoxLayout({style_class: "menu-application-box"})
this.box.add_style_class_name("starkmenu-application-box");
```
In this way the starkmenu-application-box override the properties that you define in menu-application-box, so the properties will not be override if you don't set inside the starkmenu-application-box the same properties of menu-application-box. For example:
```
menu-application-box = {
    border-width: 3px;
    width: 6px;
}
```
```
starkmenu-application-box= {
    width: 10px;
}
```
The resulting style will be in this case:
```
resulting-style = {
    border-width: 3px;
    width: 10px;
}
```
Additional you have a local(the style inside the applet) and global style(a cinnamon style define by a theme). If one global style is set for an style class, then you can not set any local style.

Example:
```
menu-application-box: global
starkmenu-application-box: local
```
Then there are no way to set the properties of the starkmenu-application-box, because is local and there are one set global.

Please see that this code are also equivalent:
```
this.box = new St.BoxLayout({ style_class: "menu-application-box"})
this.box.add_style_class_name("starkmenu-application-box");
```
```
this.box = new St.BoxLayout();
this.box.set_style_class_name("menu-application-box"); //clean all previously and set the style class.
this.box.add_style_class_name("starkmenu-application-box")// Add this style to the currents.
``` 
For more information, please see:
https://github.com/linuxmint/Cinnamon/issues/4428
https://github.com/jake-phy/WindowIconList/issues/38

**Comment by bluedxca93** [comment]
@lester
I do just have a small question:
could configurable or any other menu applet crash if the global
required css classed the applet.js uses are missing in themes.?

**Comment by lestcape** [comment]
Not

**Comment by NikoKrause** [comment]
@lestcape: Thanks. That worked great.

**Comment by sergioad** [comment]
Hi @lestcape I am also having issues with Configurable menu and cinnamon

**Comment by NikoKrause** [comment]
@lestcape:
I want to change the separator in StarkMenu. It should look like in this picture:
![bildschirmfoto vom 2016-05-16 17 15 58](https://cloud.githubusercontent.com/assets/8415124/15296619/6cb012dc-1b96-11e6-804f-5cca709480b2.png)

But I want this to change only for a specific theme. I thought it would work, if I would do something like
`add_style_class_name`. (i.e. the code should look like in the following picture, but it doesn't work this way.
![bildschirmfoto vom 2016-05-16 17 12 16](https://cloud.githubusercontent.com/assets/8415124/15296678/b5c347e6-1b96-11e6-9609-7bf0da033782.png)

Do you have any suggestions, how to handle this?
)

**Comment by bluedxca93** [comment]
what happens if a border or background image is defined for the seperator?

**Comment by NikoKrause** [comment]
@bluedxca93 
I don't know how to create such a border image.

@lestcape or somebody who knows.
I want to translate my cinnamon application CinnXPStarkMenu. What do I have to do, after I created a .po file,  which contains the translations? Do I have to add some code in applet.js?

**Comment by bluedxca93** [comment]
grep a cinnamon theme for png and svg. then you'll see how its done.

**Comment by NikoKrause** [comment]
Sorry, I already have the next question :(

This time I have a question to the settings-schema.json file.
I use a entry, which depends on an checkbox. The code looks like this:
` "quicklink-12-checkbox" : {
    "type" : "checkbox",
    "default" : true,
    "description" : "Show Quicklink in menu",
    "tooltip" : "Choose whether or not to show this Quicklink in the Quicklinks sidebar."
 },
 "quicklink-12" : {
    "type": "entry",
    "default": "Help,help,yelp",
    "description": "Quicklink",
    "tooltip": "Entry for your Quicklink. Title,icon,command. If the icon does not contain an extension then it will look for the closest icon by name in the current theme. Otherwise it will find the icon by path.",
    "dependency" : "quicklink-12-checkbox",
    "indent" : true
 },`

The result is the following:
![schema1](https://cloud.githubusercontent.com/assets/8415124/15323377/0628efb4-1c42-11e6-82f6-fcc7fd768038.png)

I want the checkbox and the entry to be side by side:
![schema2](https://cloud.githubusercontent.com/assets/8415124/15323387/135904e4-1c42-11e6-9fc2-f3ca42d99536.png)

Is there a special type, for something like this?
Or a command "linebreak": false like the "indent" command above?

**Comment by lestcape** [comment]
@NikoKrause There are not anything, to make a thing like that. I proposed create two types of boxes with a vertical and horizontal layout. Then you can create a composition of your own setting layout, using a composition of boxes with the actual components inside some of them, but is not implemented.

**Comment by NikoKrause** [comment]
@lestcape 
Thanks for your answer. I think this is a little bit to difficult for me right now. Maybe after I gained more experience in coding I look back into it.

**Comment by lestcape** [comment]
@NikoKrause not. Is more simple, you can not do anything, because the change need to be done inside the cinnamon-settings first, then you could use the new functionalities.
