### ISSUE TITLE
Web Search

### ISSUE THREAD

**Issue by lucidb-x** [lestcape/Configurable-Menu#87]
Hola letscape. I enabled Web Search with google in the configuration. But I do not see it working in the menu. I tried different themes and there is no web search for me to use.

 I read the Issues #44.
Does this work? 
(...(http://www.google.com/search?q=) i try change line 9747 it works good...)
How do I do what nfat is saying on line 9747?

**Comment by lestcape** [comment]
I don't use the google standard url because the the mint team have one an they receive a portion of money per visitors, so is a way of made a contribution to the project. WebSearch is disable by default, so, is your decision if you want to use this feature or not. I never ask to @clefebvre if this is useful or not. In any case Configurable Menu is out of cinnamon 2.8, so this problem have not priority now and also there are an implementation to handled Search in cinnamon(just is not enable for now), so will not be implemented a complete alternative way to search thing. In all case i will contribute to be better the actually.

**Comment by lestcape** [comment]
This extension have not support for Cinnamon, as all extensions was forked by Clement and I don't want to work in this conditions. Will be aviable from Gnome Shell Desktop.
